apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sidecar-injector.fullname" . }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ tpl .Values.config . | indent 4 }}
