apiVersion: v1
kind: Service
metadata:
  name: {{ include "sidecar-injector.fullname" . }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
    {{- include "sidecar-injector.serviceLabels" . | nindent 4 }}
  annotations:
    {{- include "sidecar-injector.serviceAnnotations" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "sidecar-injector.selectorLabels" . | nindent 4 }}
